name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: firebase-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            functions/package-lock.json
            hosting/package-lock.json

      - name: Install Functions deps
        run: npm ci
        working-directory: functions

      - name: Install Hosting deps
        run: npm ci
        working-directory: hosting

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          firebase deploy --only firestore,functions,hosting --project "$FIREBASE_PROJECT_ID" --non-interactive


